Project structure refactoring
medegor44/spotify-playlist pull request #23
Opened 2021-03-26 16:46 UTC by medegor44

2021-03-27 09:19 UTC, confirmit-horizons requested changes

2021-03-27 09:19 UTC, confirmit-horizons commented on src/components/app/App.jsx
>  import Content from "./Content";
/app folder is not really needed, you can just put all components from /app to the /components folder

2021-03-27 09:19 UTC, confirmit-horizons commented on src/components/app/Header.jsx
> +        <a href="../..">spotify playlist</a>
Looks strange. Why not just '/'?

2021-03-27 09:19 UTC, confirmit-horizons commented on src/components/contentSection/SearchManager.jsx
> +import ResponsesContainer from "./searchResultsSection/ResponsesContainer";
- 'Section' postfix can be removed. /search-results/SearchForm is much better.

- Also CamelCase notation usually used for jsx components (ie ResponsesContainer.jsx), but all other js files and folders usually used all-lowercase with '-' delimiters. For example, searchResults -> search-results etc

2021-03-27 09:19 UTC, confirmit-horizons commented on src/components/contentSection/createPlaylistSection/CreatePlaylistForm.jsx
> +import React, { useState } from "react";
/contentSection can just be removed. 
Folder structure could be:
/components
-- /login
-- /user-info
-- /search-form
-- /search-results
-- /create-playlist

Using proper component grouping will make it easier to change the UI later.

2021-03-27 09:19 UTC, confirmit-horizons commented on src/index.jsx
>  import React from "react";
also would be good to extract /utils/spotify.js with all dependencies to a separate folder. For example, /spotify-client/. and add index.js with needed exports

2021-03-29 06:55 UTC, medegor44 commented on src/components/contentSection/SearchManager.jsx
> +const SearchManager = () => {
Generic name "...Manager". Code smell.

2021-03-29 07:10 UTC, medegor44 commented on src/components/app/Header.jsx
> +        <a href="../..">spotify playlist</a>
This strange path appeared after WebStrom's auto refactoring. I have fixed this yet.

2021-04-01 14:51 UTC, confirmit-horizons approved these changes

2021-04-05 12:51 UTC, merged