Search manager refactoring from actual master
medegor44/spotify-playlist pull request #25
Opened 2021-04-07 12:52 UTC by medegor44

2021-04-07 17:44 UTC, confirmit-horizons requested changes

2021-04-07 17:44 UTC, confirmit-horizons commented on src/components/MainContent.jsx
> +          <div className="sectionContentContainer createPlaylist">
createPlaylist classname belongs to CreatePlaylistForm component so make sense to use it inside a component. sectionContentContainer can be still outside

2021-04-07 17:44 UTC, confirmit-horizons commented on src/components/MainContent.jsx
> +import "../css/SpotifySongSearch.css";
adjust CSS filenames to fit corresponding component names they belong to

2021-04-07 17:44 UTC, confirmit-horizons commented on src/components/search-form/SearchForm.jsx
>    const [token] = useToken();
nit: you can move useToken inside performRequest as it's just a hook and it's not used anywhere else

2021-04-09 10:54 UTC, medegor44 commented on src/components/MainContent.jsx
> +          <div className="sectionContentContainer createPlaylist">
I just removed `createPlaylist` style.

2021-04-09 11:01 UTC, medegor44 commented on src/components/search-form/SearchForm.jsx
>    const [token] = useToken();
But performRequest is not a hook, it is just a callback and I can't call hook from function wich is not component.

2021-04-12 13:25 UTC, confirmit-horizons approved these changes

2021-04-17 19:09 UTC, merged